name: filebot
version: 4.7
summary: The ultimate TV and Movie Renamer / Subtitle Downloader
description: FileBot is the ultimate tool for renaming your movies, tv shows or anime and even downloading subtitles. It's smart, streamlined for simplicity and just works. Putting the super-efficient UI aside, it's also got a full-featured command-line interface and scripting engine for all sorts of automation. Anything is possible.


architectures:
- amd64


apps:
  filebot:
    command: bin/filebot
    plugs:
    - home
    - network
    - network-bind
    - network-observe
    - opengl
    - unity7
    - x11
    - locale-control


parts:
  filebot:
    plugin: copy
    files:
      filebot.sh: bin/filebot
      FileBot.jar: filebot/FileBot.jar
  fonts:
    plugin: copy
    files:
      /usr/share/fonts: usr/share/fonts
      fonts.conf: fonts.conf
  packages:
    plugin: nil
    stage-packages:
    - libmediainfo0v5
    - libchromaprint-tools
    - openjdk-8-jre
    - openjfx
    - fontconfig
    - jayatana
    - gvfs
    - mesa-utils
  loaders:
    plugin: copy
    files:
      loaders.cache: usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
    stage-packages:
    - libwmf0.2-7-gtk
    - librsvg2-common
    - libgdk-pixbuf2.0-0
