name: filebot
version: @{version}
summary: The ultimate TV and Movie Renamer / Subtitle Downloader
description: FileBot is the ultimate tool for organizing and renaming your movies, tv shows or anime, and music well as downloading subtitles and artwork. It's smart and just works.

confinement: strict

architectures: [amd64]

apps:
  filebot:
    command: desktop-launch $SNAP/filebot/filebot.sh
    plugs: [unity7, opengl, x11, home, network, network-bind, pulseaudio, gsettings]

parts:
  filebot:
    plugin: copy
    files:
      filebot: filebot
  java:
    plugin: nil
    stage-packages: [openjdk-8-jre, openjfx, jayatana]
    after: [desktop/gtk2]
  mediainfo:
    plugin: nil
    stage-packages: [libmediainfo0v5, libchromaprint-tools]
