name: filebot
version: 4.7
summary: The ultimate TV and Movie Renamer / Subtitle Downloader
description: FileBot is the ultimate tool for renaming your movies, tv shows or anime and even downloading subtitles. It's smart, streamlined for simplicity and just works. Putting the super-efficient UI aside, it's also got a full-featured command-line interface and scripting engine for all sorts of automation. Anything is possible.


architectures:
- amd64


apps:
  filebot:
    command: bin/filebot
    plugs:
    - home
    - network
    - opengl
    - unity7
    - x11


parts:
  filebot:
    plugin: copy
    files:
      filebot.sh: bin/filebot
      FileBot.jar: filebot/FileBot.jar
  oracle-java:
    plugin: copy
    files:
      oracle-java: oracle-java
  packages:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
    - fontconfig
    - gtk2-engines-murrine
    - light-themes
    - libcanberra-gtk-module
    - jayatana
    - gvfs
    - unity-gtk2-module
    - overlay-scrollbar-gtk2
#    - libmediainfo0v5
#    - libchromaprint-tools
  loaders:
    plugin: copy
    files:
      loaders.cache: usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
    stage-packages:
    - libgdk-pixbuf2.0-0
    - librsvg2-common
