name: filebot
version: 4.7
summary: The ultimate TV and Movie Renamer / Subtitle Downloader
description: FileBot is the ultimate tool for renaming your movies, tv shows or anime and even downloading subtitles. It's smart, streamlined for simplicity and just works. Putting the super-efficient UI aside, it's also got a full-featured command-line interface and scripting engine for all sorts of automation. Anything is possible.


architectures:
- amd64


apps:
  filebot:
    command: bin/filebot
    plugs:
    - home
    - network
    - network-bind
    - network-observe
    - opengl
    - unity7
    - x11
    - locale-control


parts:
  filebot:
    plugin: copy
    files:
      filebot.sh: bin/filebot
      FileBot.jar: filebot/FileBot.jar
  fonts:
    plugin: copy
    files:
      /usr/share/fonts: /usr/share/fonts
      fonts.conf: fonts.conf
  base:
    plugin: jdk
    source: .
    stage-packages:
    - libgnome2-0
    - gvfs
    - mediainfo
    - libchromaprint-tools
    - language-pack-en
    - openjfx
    - fontconfig
    - libcanberra-gtk-module
    - libcanberra-gtk0
    - libcanberra-gtk3-0
    - overlay-scrollbar
